
namespace SevenWonders.BaseEntities
{
    public enum CardName
    {
        // Raw Materials
        LumberYard = 1,
        OreVein,
        ClayPool,
        StonePit,
        TimberYard,
        ClayPit,
        Excavation,
        ForestCave,
        TreeFarm,
        Mine,
        Sawmill,
        Foundry,
        Brickyard,
        Quarry,
        // Manufactured Goods
        Loom = 101,
        Glassworks,
        Press,
        // Civilian Structure
        Altar = 201,
        Theatre,
        Baths,
        Pawnshop,
        Temple,
        Courthouse,
        Statue,
        Aqueduct,
        Gardens,
        Senate,
        TownHall,
        Pantheon,
        Palace,
        // Scientific Structure
        Apothecary = 301,
        Workshop,
        Scriptorium,
        Library,
        Laboratory,
        Dispensary,
        School,
        University,
        Observatory,
        Lodge,
        Study,
        Academy,
        // Commercial Structure
        EastTradingPost = 401,
        WestTradingPost,
        Marketplace,
        Tavern,
        Caravansery,
        Forum,
        Vineyard,
        Bazaar,
        Arena,
        Lighthouse,
        Haven,
        ChamberOfCommerce,
        // Military Structure
        Stockade = 501,
        Barracks,
        GuardTower,
        Stables,
        ArcheryRanch,
        Walls,
        TrainningGround,
        SiegeWorkshop,
        Fortification,
        Arsenal,
        Circus,
        // Guilds
        WorkersGuild = 601,
        CraftsmenGuild,
        ShipownersGuild,
        TradersGuild,
        MagistratesGuild,
        BuildersGuild,
        PhilosophersGuild,
        ScientistsGuild,
        SpiesGuild,
        StrategistsGuild,       
    }
}
